#!/bin/sh
# Generate mosquitto's password and ACL files from the environment, then hand off
# to the broker.
#
# Credentials are never committed: `mosquitto_passwd` hashes them here, into a
# writable volume, on every start. Restarting with a changed password therefore
# rotates it — the file is rebuilt from scratch rather than appended to.
set -eu

AUTH_DIR=/mosquitto/auth
PASSWD_FILE="$AUTH_DIR/passwd"
ACL_FILE="$AUTH_DIR/acl"

# Topic subtree the fleet publishes under. Must cover MQTT_TOPIC_PATTERN's root
# (default /fleet/{deviceId}/vehicle_info -> /fleet/#).
TOPIC_PATTERN="${MQTT_ACL_TOPIC_PATTERN:-/fleet/#}"

require() {
  eval "value=\${$1:-}"
  if [ -z "$value" ]; then
    echo "mosquitto-entrypoint: $1 is required (anonymous access is disabled)" >&2
    exit 1
  fi
}

require MQTT_SUBSCRIBER_USERNAME
require MQTT_SUBSCRIBER_PASSWORD
require MQTT_PUBLISHER_USERNAME
require MQTT_PUBLISHER_PASSWORD

mkdir -p "$AUTH_DIR"

# -c truncates, so the first call defines the file and the second appends.
mosquitto_passwd -c -b "$PASSWD_FILE" "$MQTT_SUBSCRIBER_USERNAME" "$MQTT_SUBSCRIBER_PASSWORD"
mosquitto_passwd -b "$PASSWD_FILE" "$MQTT_PUBLISHER_USERNAME" "$MQTT_PUBLISHER_PASSWORD"

# Least privilege in both directions: the backend only ever reads telemetry, and
# a vehicle (or the demo publisher) only ever writes it. Neither can do the
# other's job, so a leaked backend credential cannot inject fake telemetry and a
# leaked vehicle credential cannot read the rest of the fleet.
cat >"$ACL_FILE" <<EOF
# Generated by entrypoint.sh on container start — edits here are lost on restart.
user $MQTT_SUBSCRIBER_USERNAME
topic read $TOPIC_PATTERN

user $MQTT_PUBLISHER_USERNAME
topic write $TOPIC_PATTERN
EOF

# mosquitto refuses a group- or world-readable password file. Ownership matters
# too: this script runs as root (the image declares no USER), while the broker
# drops to uid 1883 *after* loading its config and only then opens these files —
# root-owned 0600 files produce "Error: Unable to open pwfile".
chown mosquitto:mosquitto "$AUTH_DIR" "$PASSWD_FILE" "$ACL_FILE"
chmod 600 "$PASSWD_FILE"
chmod 640 "$ACL_FILE"

exec /usr/sbin/mosquitto -c /mosquitto/config/mosquitto.conf
